title: Daily News Digest
description: >-
  Eine kuratierte t√§gliche AI-Nachrichtenzusammenfassung mit den wichtigsten Geschichten und Artikeln aus dem Internet, jeden Tag frisch geliefert.

domain: fbrinker.github.io
baseurl: /github-pages-daily-news-digest/
url: https://fbrinker.github.io

timezone: Europe/Berlin

theme: null

markdown: kramdown

# Show posts with future dates
future: false

collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
